// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: dtako_rows_aggregation.proto

package dtako_rows_aggregation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 月次給油量サマリー
type MonthlyFuelSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CarCc             string                 `protobuf:"bytes,1,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`                                         // 車輌CC
	YearMonth         string                 `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`                             // 年月 (YYYY-MM形式)
	TotalDistance     float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`               // 総走行距離 (km)
	TotalFuel         float64                `protobuf:"fixed64,4,opt,name=total_fuel,json=totalFuel,proto3" json:"total_fuel,omitempty"`                           // 総給油量 (L)
	TripCount         int32                  `protobuf:"varint,5,opt,name=trip_count,json=tripCount,proto3" json:"trip_count,omitempty"`                            // 運行回数
	AvgFuelEfficiency float64                `protobuf:"fixed64,6,opt,name=avg_fuel_efficiency,json=avgFuelEfficiency,proto3" json:"avg_fuel_efficiency,omitempty"` // 平均燃費 (km/L)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MonthlyFuelSummary) Reset() {
	*x = MonthlyFuelSummary{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyFuelSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyFuelSummary) ProtoMessage() {}

func (x *MonthlyFuelSummary) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyFuelSummary.ProtoReflect.Descriptor instead.
func (*MonthlyFuelSummary) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{0}
}

func (x *MonthlyFuelSummary) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *MonthlyFuelSummary) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *MonthlyFuelSummary) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *MonthlyFuelSummary) GetTotalFuel() float64 {
	if x != nil {
		return x.TotalFuel
	}
	return 0
}

func (x *MonthlyFuelSummary) GetTripCount() int32 {
	if x != nil {
		return x.TripCount
	}
	return 0
}

func (x *MonthlyFuelSummary) GetAvgFuelEfficiency() float64 {
	if x != nil {
		return x.AvgFuelEfficiency
	}
	return 0
}

// 月次給油量取得リクエスト
type GetMonthlyFuelConsumptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarCc         string                 `protobuf:"bytes,1,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`             // 車輌CC（必須）
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 開始日 (YYYY-MM-DD)
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 終了日 (YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMonthlyFuelConsumptionRequest) Reset() {
	*x = GetMonthlyFuelConsumptionRequest{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMonthlyFuelConsumptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMonthlyFuelConsumptionRequest) ProtoMessage() {}

func (x *GetMonthlyFuelConsumptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMonthlyFuelConsumptionRequest.ProtoReflect.Descriptor instead.
func (*GetMonthlyFuelConsumptionRequest) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{1}
}

func (x *GetMonthlyFuelConsumptionRequest) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *GetMonthlyFuelConsumptionRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetMonthlyFuelConsumptionRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// 月次給油量取得レスポンス
type MonthlyFuelConsumptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*MonthlyFuelSummary  `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	CarCc         string                 `protobuf:"bytes,2,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"` // 集計期間
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyFuelConsumptionResponse) Reset() {
	*x = MonthlyFuelConsumptionResponse{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyFuelConsumptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyFuelConsumptionResponse) ProtoMessage() {}

func (x *MonthlyFuelConsumptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyFuelConsumptionResponse.ProtoReflect.Descriptor instead.
func (*MonthlyFuelConsumptionResponse) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{2}
}

func (x *MonthlyFuelConsumptionResponse) GetSummaries() []*MonthlyFuelSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

func (x *MonthlyFuelConsumptionResponse) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *MonthlyFuelConsumptionResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// 全車両月次サマリー取得リクエスト
type GetVehicleMonthlySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 開始日 (YYYY-MM-DD)
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 終了日 (YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleMonthlySummaryRequest) Reset() {
	*x = GetVehicleMonthlySummaryRequest{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleMonthlySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleMonthlySummaryRequest) ProtoMessage() {}

func (x *GetVehicleMonthlySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleMonthlySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleMonthlySummaryRequest) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{3}
}

func (x *GetVehicleMonthlySummaryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetVehicleMonthlySummaryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// 車両別月次データ
type VehicleMonthlySummaries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarCc         string                 `protobuf:"bytes,1,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`
	Summaries     []*MonthlyFuelSummary  `protobuf:"bytes,2,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleMonthlySummaries) Reset() {
	*x = VehicleMonthlySummaries{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMonthlySummaries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMonthlySummaries) ProtoMessage() {}

func (x *VehicleMonthlySummaries) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMonthlySummaries.ProtoReflect.Descriptor instead.
func (*VehicleMonthlySummaries) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{4}
}

func (x *VehicleMonthlySummaries) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *VehicleMonthlySummaries) GetSummaries() []*MonthlyFuelSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

// 全車両月次サマリーレスポンス
type VehicleMonthlySummaryResponse struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	VehicleSummaries []*VehicleMonthlySummaries `protobuf:"bytes,1,rep,name=vehicle_summaries,json=vehicleSummaries,proto3" json:"vehicle_summaries,omitempty"`
	TotalVehicles    int32                      `protobuf:"varint,2,opt,name=total_vehicles,json=totalVehicles,proto3" json:"total_vehicles,omitempty"`
	Period           string                     `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VehicleMonthlySummaryResponse) Reset() {
	*x = VehicleMonthlySummaryResponse{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleMonthlySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleMonthlySummaryResponse) ProtoMessage() {}

func (x *VehicleMonthlySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleMonthlySummaryResponse.ProtoReflect.Descriptor instead.
func (*VehicleMonthlySummaryResponse) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{5}
}

func (x *VehicleMonthlySummaryResponse) GetVehicleSummaries() []*VehicleMonthlySummaries {
	if x != nil {
		return x.VehicleSummaries
	}
	return nil
}

func (x *VehicleMonthlySummaryResponse) GetTotalVehicles() int32 {
	if x != nil {
		return x.TotalVehicles
	}
	return 0
}

func (x *VehicleMonthlySummaryResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// 日次サマリー取得リクエスト
type GetDailySummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarCc         string                 `protobuf:"bytes,1,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`             // 車輌CC（必須）
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // 開始日 (YYYY-MM-DD)
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // 終了日 (YYYY-MM-DD)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDailySummaryRequest) Reset() {
	*x = GetDailySummaryRequest{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDailySummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailySummaryRequest) ProtoMessage() {}

func (x *GetDailySummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailySummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDailySummaryRequest) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{6}
}

func (x *GetDailySummaryRequest) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *GetDailySummaryRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetDailySummaryRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// 日次サマリー
type DailySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarCc         string                 `protobuf:"bytes,1,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`                                          // 日付 (YYYY-MM-DD)
	TotalDistance float64                `protobuf:"fixed64,3,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"` // 走行距離
	TotalFuel     float64                `protobuf:"fixed64,4,opt,name=total_fuel,json=totalFuel,proto3" json:"total_fuel,omitempty"`             // 給油量
	TripCount     int32                  `protobuf:"varint,5,opt,name=trip_count,json=tripCount,proto3" json:"trip_count,omitempty"`              // 運行回数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySummary) Reset() {
	*x = DailySummary{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySummary) ProtoMessage() {}

func (x *DailySummary) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySummary.ProtoReflect.Descriptor instead.
func (*DailySummary) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{7}
}

func (x *DailySummary) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *DailySummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailySummary) GetTotalDistance() float64 {
	if x != nil {
		return x.TotalDistance
	}
	return 0
}

func (x *DailySummary) GetTotalFuel() float64 {
	if x != nil {
		return x.TotalFuel
	}
	return 0
}

func (x *DailySummary) GetTripCount() int32 {
	if x != nil {
		return x.TripCount
	}
	return 0
}

// 日次サマリーレスポンス
type DailySummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*DailySummary        `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	CarCc         string                 `protobuf:"bytes,2,opt,name=car_cc,json=carCc,proto3" json:"car_cc,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailySummaryResponse) Reset() {
	*x = DailySummaryResponse{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailySummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailySummaryResponse) ProtoMessage() {}

func (x *DailySummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailySummaryResponse.ProtoReflect.Descriptor instead.
func (*DailySummaryResponse) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{8}
}

func (x *DailySummaryResponse) GetSummaries() []*DailySummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

func (x *DailySummaryResponse) GetCarCc() string {
	if x != nil {
		return x.CarCc
	}
	return ""
}

func (x *DailySummaryResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

// CSVエクスポートレスポンス
type ExportCSVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsvData       string                 `protobuf:"bytes,1,opt,name=csv_data,json=csvData,proto3" json:"csv_data,omitempty"` // CSV形式のデータ
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`              // 推奨ファイル名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportCSVResponse) Reset() {
	*x = ExportCSVResponse{}
	mi := &file_dtako_rows_aggregation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportCSVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportCSVResponse) ProtoMessage() {}

func (x *ExportCSVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dtako_rows_aggregation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportCSVResponse.ProtoReflect.Descriptor instead.
func (*ExportCSVResponse) Descriptor() ([]byte, []int) {
	return file_dtako_rows_aggregation_proto_rawDescGZIP(), []int{9}
}

func (x *ExportCSVResponse) GetCsvData() string {
	if x != nil {
		return x.CsvData
	}
	return ""
}

func (x *ExportCSVResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_dtako_rows_aggregation_proto protoreflect.FileDescriptor

const file_dtako_rows_aggregation_proto_rawDesc = "" +
	"\n" +
	"\x1cdtako_rows_aggregation.proto\x12\x16dtako_rows_aggregation\"\xdf\x01\n" +
	"\x12MonthlyFuelSummary\x12\x15\n" +
	"\x06car_cc\x18\x01 \x01(\tR\x05carCc\x12\x1d\n" +
	"\n" +
	"year_month\x18\x02 \x01(\tR\tyearMonth\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12\x1d\n" +
	"\n" +
	"total_fuel\x18\x04 \x01(\x01R\ttotalFuel\x12\x1d\n" +
	"\n" +
	"trip_count\x18\x05 \x01(\x05R\ttripCount\x12.\n" +
	"\x13avg_fuel_efficiency\x18\x06 \x01(\x01R\x11avgFuelEfficiency\"s\n" +
	" GetMonthlyFuelConsumptionRequest\x12\x15\n" +
	"\x06car_cc\x18\x01 \x01(\tR\x05carCc\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x99\x01\n" +
	"\x1eMonthlyFuelConsumptionResponse\x12H\n" +
	"\tsummaries\x18\x01 \x03(\v2*.dtako_rows_aggregation.MonthlyFuelSummaryR\tsummaries\x12\x15\n" +
	"\x06car_cc\x18\x02 \x01(\tR\x05carCc\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"[\n" +
	"\x1fGetVehicleMonthlySummaryRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"z\n" +
	"\x17VehicleMonthlySummaries\x12\x15\n" +
	"\x06car_cc\x18\x01 \x01(\tR\x05carCc\x12H\n" +
	"\tsummaries\x18\x02 \x03(\v2*.dtako_rows_aggregation.MonthlyFuelSummaryR\tsummaries\"\xbc\x01\n" +
	"\x1dVehicleMonthlySummaryResponse\x12\\\n" +
	"\x11vehicle_summaries\x18\x01 \x03(\v2/.dtako_rows_aggregation.VehicleMonthlySummariesR\x10vehicleSummaries\x12%\n" +
	"\x0etotal_vehicles\x18\x02 \x01(\x05R\rtotalVehicles\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"i\n" +
	"\x16GetDailySummaryRequest\x12\x15\n" +
	"\x06car_cc\x18\x01 \x01(\tR\x05carCc\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"\x9e\x01\n" +
	"\fDailySummary\x12\x15\n" +
	"\x06car_cc\x18\x01 \x01(\tR\x05carCc\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12%\n" +
	"\x0etotal_distance\x18\x03 \x01(\x01R\rtotalDistance\x12\x1d\n" +
	"\n" +
	"total_fuel\x18\x04 \x01(\x01R\ttotalFuel\x12\x1d\n" +
	"\n" +
	"trip_count\x18\x05 \x01(\x05R\ttripCount\"\x89\x01\n" +
	"\x14DailySummaryResponse\x12B\n" +
	"\tsummaries\x18\x01 \x03(\v2$.dtako_rows_aggregation.DailySummaryR\tsummaries\x12\x15\n" +
	"\x06car_cc\x18\x02 \x01(\tR\x05carCc\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\"J\n" +
	"\x11ExportCSVResponse\x12\x19\n" +
	"\bcsv_data\x18\x01 \x01(\tR\acsvData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename2\xa8\x04\n" +
	"\x1bDtakoRowsAggregationService\x12\x8d\x01\n" +
	"\x19GetMonthlyFuelConsumption\x128.dtako_rows_aggregation.GetMonthlyFuelConsumptionRequest\x1a6.dtako_rows_aggregation.MonthlyFuelConsumptionResponse\x12\x8a\x01\n" +
	"\x18GetVehicleMonthlySummary\x127.dtako_rows_aggregation.GetVehicleMonthlySummaryRequest\x1a5.dtako_rows_aggregation.VehicleMonthlySummaryResponse\x12o\n" +
	"\x0fGetDailySummary\x12..dtako_rows_aggregation.GetDailySummaryRequest\x1a,.dtako_rows_aggregation.DailySummaryResponse\x12{\n" +
	"\x14ExportMonthlyFuelCSV\x128.dtako_rows_aggregation.GetMonthlyFuelConsumptionRequest\x1a).dtako_rows_aggregation.ExportCSVResponseBEZCgithub.com/yhonda-ohishi/dtako_rows/v3/proto;dtako_rows_aggregationb\x06proto3"

var (
	file_dtako_rows_aggregation_proto_rawDescOnce sync.Once
	file_dtako_rows_aggregation_proto_rawDescData []byte
)

func file_dtako_rows_aggregation_proto_rawDescGZIP() []byte {
	file_dtako_rows_aggregation_proto_rawDescOnce.Do(func() {
		file_dtako_rows_aggregation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dtako_rows_aggregation_proto_rawDesc), len(file_dtako_rows_aggregation_proto_rawDesc)))
	})
	return file_dtako_rows_aggregation_proto_rawDescData
}

var file_dtako_rows_aggregation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dtako_rows_aggregation_proto_goTypes = []any{
	(*MonthlyFuelSummary)(nil),               // 0: dtako_rows_aggregation.MonthlyFuelSummary
	(*GetMonthlyFuelConsumptionRequest)(nil), // 1: dtako_rows_aggregation.GetMonthlyFuelConsumptionRequest
	(*MonthlyFuelConsumptionResponse)(nil),   // 2: dtako_rows_aggregation.MonthlyFuelConsumptionResponse
	(*GetVehicleMonthlySummaryRequest)(nil),  // 3: dtako_rows_aggregation.GetVehicleMonthlySummaryRequest
	(*VehicleMonthlySummaries)(nil),          // 4: dtako_rows_aggregation.VehicleMonthlySummaries
	(*VehicleMonthlySummaryResponse)(nil),    // 5: dtako_rows_aggregation.VehicleMonthlySummaryResponse
	(*GetDailySummaryRequest)(nil),           // 6: dtako_rows_aggregation.GetDailySummaryRequest
	(*DailySummary)(nil),                     // 7: dtako_rows_aggregation.DailySummary
	(*DailySummaryResponse)(nil),             // 8: dtako_rows_aggregation.DailySummaryResponse
	(*ExportCSVResponse)(nil),                // 9: dtako_rows_aggregation.ExportCSVResponse
}
var file_dtako_rows_aggregation_proto_depIdxs = []int32{
	0, // 0: dtako_rows_aggregation.MonthlyFuelConsumptionResponse.summaries:type_name -> dtako_rows_aggregation.MonthlyFuelSummary
	0, // 1: dtako_rows_aggregation.VehicleMonthlySummaries.summaries:type_name -> dtako_rows_aggregation.MonthlyFuelSummary
	4, // 2: dtako_rows_aggregation.VehicleMonthlySummaryResponse.vehicle_summaries:type_name -> dtako_rows_aggregation.VehicleMonthlySummaries
	7, // 3: dtako_rows_aggregation.DailySummaryResponse.summaries:type_name -> dtako_rows_aggregation.DailySummary
	1, // 4: dtako_rows_aggregation.DtakoRowsAggregationService.GetMonthlyFuelConsumption:input_type -> dtako_rows_aggregation.GetMonthlyFuelConsumptionRequest
	3, // 5: dtako_rows_aggregation.DtakoRowsAggregationService.GetVehicleMonthlySummary:input_type -> dtako_rows_aggregation.GetVehicleMonthlySummaryRequest
	6, // 6: dtako_rows_aggregation.DtakoRowsAggregationService.GetDailySummary:input_type -> dtako_rows_aggregation.GetDailySummaryRequest
	1, // 7: dtako_rows_aggregation.DtakoRowsAggregationService.ExportMonthlyFuelCSV:input_type -> dtako_rows_aggregation.GetMonthlyFuelConsumptionRequest
	2, // 8: dtako_rows_aggregation.DtakoRowsAggregationService.GetMonthlyFuelConsumption:output_type -> dtako_rows_aggregation.MonthlyFuelConsumptionResponse
	5, // 9: dtako_rows_aggregation.DtakoRowsAggregationService.GetVehicleMonthlySummary:output_type -> dtako_rows_aggregation.VehicleMonthlySummaryResponse
	8, // 10: dtako_rows_aggregation.DtakoRowsAggregationService.GetDailySummary:output_type -> dtako_rows_aggregation.DailySummaryResponse
	9, // 11: dtako_rows_aggregation.DtakoRowsAggregationService.ExportMonthlyFuelCSV:output_type -> dtako_rows_aggregation.ExportCSVResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_dtako_rows_aggregation_proto_init() }
func file_dtako_rows_aggregation_proto_init() {
	if File_dtako_rows_aggregation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dtako_rows_aggregation_proto_rawDesc), len(file_dtako_rows_aggregation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dtako_rows_aggregation_proto_goTypes,
		DependencyIndexes: file_dtako_rows_aggregation_proto_depIdxs,
		MessageInfos:      file_dtako_rows_aggregation_proto_msgTypes,
	}.Build()
	File_dtako_rows_aggregation_proto = out.File
	file_dtako_rows_aggregation_proto_goTypes = nil
	file_dtako_rows_aggregation_proto_depIdxs = nil
}
