// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/dtako_rows.proto

package dtako_rows

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 運行データ
type DtakoRow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                              // 主キー
	UnkoNo             string                 `protobuf:"bytes,2,opt,name=unko_no,json=unkoNo,proto3" json:"unko_no,omitempty"`                                        // 運行NO
	SharyouCc          string                 `protobuf:"bytes,3,opt,name=sharyou_cc,json=sharyouCc,proto3" json:"sharyou_cc,omitempty"`                               // 車輌CC
	JomuinCd1          string                 `protobuf:"bytes,4,opt,name=jomuin_cd1,json=jomuinCd1,proto3" json:"jomuin_cd1,omitempty"`                               // 乗務員CD1
	ShukkoDatetime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=shukko_datetime,json=shukkoDatetime,proto3" json:"shukko_datetime,omitempty"`                // 出庫日時
	KikoDatetime       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=kiko_datetime,json=kikoDatetime,proto3" json:"kiko_datetime,omitempty"`                      // 帰庫日時
	UnkoDate           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=unko_date,json=unkoDate,proto3" json:"unko_date,omitempty"`                                  // 運行日
	TaishouJomuinKubun int32                  `protobuf:"varint,8,opt,name=taishou_jomuin_kubun,json=taishouJomuinKubun,proto3" json:"taishou_jomuin_kubun,omitempty"` // 対象乗務員区分
	SoukouKyori        float64                `protobuf:"fixed64,9,opt,name=soukou_kyori,json=soukouKyori,proto3" json:"soukou_kyori,omitempty"`                       // 走行距離
	NenryouShiyou      float64                `protobuf:"fixed64,10,opt,name=nenryou_shiyou,json=nenryouShiyou,proto3" json:"nenryou_shiyou,omitempty"`                // 燃料使用量
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                              // 作成日時
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                              // 更新日時
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DtakoRow) Reset() {
	*x = DtakoRow{}
	mi := &file_proto_dtako_rows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtakoRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtakoRow) ProtoMessage() {}

func (x *DtakoRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtakoRow.ProtoReflect.Descriptor instead.
func (*DtakoRow) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{0}
}

func (x *DtakoRow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DtakoRow) GetUnkoNo() string {
	if x != nil {
		return x.UnkoNo
	}
	return ""
}

func (x *DtakoRow) GetSharyouCc() string {
	if x != nil {
		return x.SharyouCc
	}
	return ""
}

func (x *DtakoRow) GetJomuinCd1() string {
	if x != nil {
		return x.JomuinCd1
	}
	return ""
}

func (x *DtakoRow) GetShukkoDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.ShukkoDatetime
	}
	return nil
}

func (x *DtakoRow) GetKikoDatetime() *timestamppb.Timestamp {
	if x != nil {
		return x.KikoDatetime
	}
	return nil
}

func (x *DtakoRow) GetUnkoDate() *timestamppb.Timestamp {
	if x != nil {
		return x.UnkoDate
	}
	return nil
}

func (x *DtakoRow) GetTaishouJomuinKubun() int32 {
	if x != nil {
		return x.TaishouJomuinKubun
	}
	return 0
}

func (x *DtakoRow) GetSoukouKyori() float64 {
	if x != nil {
		return x.SoukouKyori
	}
	return 0
}

func (x *DtakoRow) GetNenryouShiyou() float64 {
	if x != nil {
		return x.NenryouShiyou
	}
	return 0
}

func (x *DtakoRow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DtakoRow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetRow
type GetRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRowRequest) Reset() {
	*x = GetRowRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowRequest) ProtoMessage() {}

func (x *GetRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRowRequest.ProtoReflect.Descriptor instead.
func (*GetRowRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{1}
}

func (x *GetRowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *DtakoRow              `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRowResponse) Reset() {
	*x = GetRowResponse{}
	mi := &file_proto_dtako_rows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRowResponse) ProtoMessage() {}

func (x *GetRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRowResponse.ProtoReflect.Descriptor instead.
func (*GetRowResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{2}
}

func (x *GetRowResponse) GetRow() *DtakoRow {
	if x != nil {
		return x.Row
	}
	return nil
}

// ListRows
type ListRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	OrderBy       string                 `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRowsRequest) Reset() {
	*x = ListRowsRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRowsRequest) ProtoMessage() {}

func (x *ListRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRowsRequest.ProtoReflect.Descriptor instead.
func (*ListRowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{3}
}

func (x *ListRowsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRowsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRowsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*DtakoRow            `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRowsResponse) Reset() {
	*x = ListRowsResponse{}
	mi := &file_proto_dtako_rows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRowsResponse) ProtoMessage() {}

func (x *ListRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRowsResponse.ProtoReflect.Descriptor instead.
func (*ListRowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{4}
}

func (x *ListRowsResponse) GetRows() []*DtakoRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListRowsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListRowsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRowsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// CreateRow
type CreateRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *DtakoRow              `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRowRequest) Reset() {
	*x = CreateRowRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRowRequest) ProtoMessage() {}

func (x *CreateRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRowRequest.ProtoReflect.Descriptor instead.
func (*CreateRowRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRowRequest) GetRow() *DtakoRow {
	if x != nil {
		return x.Row
	}
	return nil
}

type CreateRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *DtakoRow              `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRowResponse) Reset() {
	*x = CreateRowResponse{}
	mi := &file_proto_dtako_rows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRowResponse) ProtoMessage() {}

func (x *CreateRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRowResponse.ProtoReflect.Descriptor instead.
func (*CreateRowResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRowResponse) GetRow() *DtakoRow {
	if x != nil {
		return x.Row
	}
	return nil
}

// UpdateRow
type UpdateRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *DtakoRow              `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRowRequest) Reset() {
	*x = UpdateRowRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRowRequest) ProtoMessage() {}

func (x *UpdateRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRowRequest.ProtoReflect.Descriptor instead.
func (*UpdateRowRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateRowRequest) GetRow() *DtakoRow {
	if x != nil {
		return x.Row
	}
	return nil
}

type UpdateRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           *DtakoRow              `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRowResponse) Reset() {
	*x = UpdateRowResponse{}
	mi := &file_proto_dtako_rows_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRowResponse) ProtoMessage() {}

func (x *UpdateRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRowResponse.ProtoReflect.Descriptor instead.
func (*UpdateRowResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRowResponse) GetRow() *DtakoRow {
	if x != nil {
		return x.Row
	}
	return nil
}

// DeleteRow
type DeleteRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRowRequest) Reset() {
	*x = DeleteRowRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRowRequest) ProtoMessage() {}

func (x *DeleteRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRowRequest.ProtoReflect.Descriptor instead.
func (*DeleteRowRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRowRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRowResponse) Reset() {
	*x = DeleteRowResponse{}
	mi := &file_proto_dtako_rows_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRowResponse) ProtoMessage() {}

func (x *DeleteRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRowResponse.ProtoReflect.Descriptor instead.
func (*DeleteRowResponse) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchRows
type SearchRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	SharyouCc     string                 `protobuf:"bytes,3,opt,name=sharyou_cc,json=sharyouCc,proto3" json:"sharyou_cc,omitempty"`
	JomuinCd1     string                 `protobuf:"bytes,4,opt,name=jomuin_cd1,json=jomuinCd1,proto3" json:"jomuin_cd1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRowsRequest) Reset() {
	*x = SearchRowsRequest{}
	mi := &file_proto_dtako_rows_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRowsRequest) ProtoMessage() {}

func (x *SearchRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dtako_rows_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRowsRequest.ProtoReflect.Descriptor instead.
func (*SearchRowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_dtako_rows_proto_rawDescGZIP(), []int{11}
}

func (x *SearchRowsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *SearchRowsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *SearchRowsRequest) GetSharyouCc() string {
	if x != nil {
		return x.SharyouCc
	}
	return ""
}

func (x *SearchRowsRequest) GetJomuinCd1() string {
	if x != nil {
		return x.JomuinCd1
	}
	return ""
}

var File_proto_dtako_rows_proto protoreflect.FileDescriptor

const file_proto_dtako_rows_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dtako_rows.proto\x12\n" +
	"dtako_rows\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x04\n" +
	"\bDtakoRow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aunko_no\x18\x02 \x01(\tR\x06unkoNo\x12\x1d\n" +
	"\n" +
	"sharyou_cc\x18\x03 \x01(\tR\tsharyouCc\x12\x1d\n" +
	"\n" +
	"jomuin_cd1\x18\x04 \x01(\tR\tjomuinCd1\x12C\n" +
	"\x0fshukko_datetime\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eshukkoDatetime\x12?\n" +
	"\rkiko_datetime\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fkikoDatetime\x127\n" +
	"\tunko_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bunkoDate\x120\n" +
	"\x14taishou_jomuin_kubun\x18\b \x01(\x05R\x12taishouJomuinKubun\x12!\n" +
	"\fsoukou_kyori\x18\t \x01(\x01R\vsoukouKyori\x12%\n" +
	"\x0enenryou_shiyou\x18\n" +
	" \x01(\x01R\rnenryouShiyou\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1f\n" +
	"\rGetRowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0eGetRowResponse\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.dtako_rows.DtakoRowR\x03row\"]\n" +
	"\x0fListRowsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x19\n" +
	"\border_by\x18\x03 \x01(\tR\aorderBy\"\x83\x01\n" +
	"\x10ListRowsResponse\x12(\n" +
	"\x04rows\x18\x01 \x03(\v2\x14.dtako_rows.DtakoRowR\x04rows\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\":\n" +
	"\x10CreateRowRequest\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.dtako_rows.DtakoRowR\x03row\";\n" +
	"\x11CreateRowResponse\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.dtako_rows.DtakoRowR\x03row\":\n" +
	"\x10UpdateRowRequest\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.dtako_rows.DtakoRowR\x03row\";\n" +
	"\x11UpdateRowResponse\x12&\n" +
	"\x03row\x18\x01 \x01(\v2\x14.dtako_rows.DtakoRowR\x03row\"\"\n" +
	"\x10DeleteRowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteRowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbf\x01\n" +
	"\x11SearchRowsRequest\x127\n" +
	"\tdate_from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bdateFrom\x123\n" +
	"\adate_to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06dateTo\x12\x1d\n" +
	"\n" +
	"sharyou_cc\x18\x03 \x01(\tR\tsharyouCc\x12\x1d\n" +
	"\n" +
	"jomuin_cd1\x18\x04 \x01(\tR\tjomuinCd12\xc3\x03\n" +
	"\x10DtakoRowsService\x12?\n" +
	"\x06GetRow\x12\x19.dtako_rows.GetRowRequest\x1a\x1a.dtako_rows.GetRowResponse\x12E\n" +
	"\bListRows\x12\x1b.dtako_rows.ListRowsRequest\x1a\x1c.dtako_rows.ListRowsResponse\x12H\n" +
	"\tCreateRow\x12\x1c.dtako_rows.CreateRowRequest\x1a\x1d.dtako_rows.CreateRowResponse\x12H\n" +
	"\tUpdateRow\x12\x1c.dtako_rows.UpdateRowRequest\x1a\x1d.dtako_rows.UpdateRowResponse\x12H\n" +
	"\tDeleteRow\x12\x1c.dtako_rows.DeleteRowRequest\x1a\x1d.dtako_rows.DeleteRowResponse\x12I\n" +
	"\n" +
	"SearchRows\x12\x1d.dtako_rows.SearchRowsRequest\x1a\x1c.dtako_rows.ListRowsResponseB9Z7github.com/yhonda-ohishi/dtako_rows/v2/proto;dtako_rowsb\x06proto3"

var (
	file_proto_dtako_rows_proto_rawDescOnce sync.Once
	file_proto_dtako_rows_proto_rawDescData []byte
)

func file_proto_dtako_rows_proto_rawDescGZIP() []byte {
	file_proto_dtako_rows_proto_rawDescOnce.Do(func() {
		file_proto_dtako_rows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dtako_rows_proto_rawDesc), len(file_proto_dtako_rows_proto_rawDesc)))
	})
	return file_proto_dtako_rows_proto_rawDescData
}

var file_proto_dtako_rows_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_dtako_rows_proto_goTypes = []any{
	(*DtakoRow)(nil),              // 0: dtako_rows.DtakoRow
	(*GetRowRequest)(nil),         // 1: dtako_rows.GetRowRequest
	(*GetRowResponse)(nil),        // 2: dtako_rows.GetRowResponse
	(*ListRowsRequest)(nil),       // 3: dtako_rows.ListRowsRequest
	(*ListRowsResponse)(nil),      // 4: dtako_rows.ListRowsResponse
	(*CreateRowRequest)(nil),      // 5: dtako_rows.CreateRowRequest
	(*CreateRowResponse)(nil),     // 6: dtako_rows.CreateRowResponse
	(*UpdateRowRequest)(nil),      // 7: dtako_rows.UpdateRowRequest
	(*UpdateRowResponse)(nil),     // 8: dtako_rows.UpdateRowResponse
	(*DeleteRowRequest)(nil),      // 9: dtako_rows.DeleteRowRequest
	(*DeleteRowResponse)(nil),     // 10: dtako_rows.DeleteRowResponse
	(*SearchRowsRequest)(nil),     // 11: dtako_rows.SearchRowsRequest
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_proto_dtako_rows_proto_depIdxs = []int32{
	12, // 0: dtako_rows.DtakoRow.shukko_datetime:type_name -> google.protobuf.Timestamp
	12, // 1: dtako_rows.DtakoRow.kiko_datetime:type_name -> google.protobuf.Timestamp
	12, // 2: dtako_rows.DtakoRow.unko_date:type_name -> google.protobuf.Timestamp
	12, // 3: dtako_rows.DtakoRow.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: dtako_rows.DtakoRow.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: dtako_rows.GetRowResponse.row:type_name -> dtako_rows.DtakoRow
	0,  // 6: dtako_rows.ListRowsResponse.rows:type_name -> dtako_rows.DtakoRow
	0,  // 7: dtako_rows.CreateRowRequest.row:type_name -> dtako_rows.DtakoRow
	0,  // 8: dtako_rows.CreateRowResponse.row:type_name -> dtako_rows.DtakoRow
	0,  // 9: dtako_rows.UpdateRowRequest.row:type_name -> dtako_rows.DtakoRow
	0,  // 10: dtako_rows.UpdateRowResponse.row:type_name -> dtako_rows.DtakoRow
	12, // 11: dtako_rows.SearchRowsRequest.date_from:type_name -> google.protobuf.Timestamp
	12, // 12: dtako_rows.SearchRowsRequest.date_to:type_name -> google.protobuf.Timestamp
	1,  // 13: dtako_rows.DtakoRowsService.GetRow:input_type -> dtako_rows.GetRowRequest
	3,  // 14: dtako_rows.DtakoRowsService.ListRows:input_type -> dtako_rows.ListRowsRequest
	5,  // 15: dtako_rows.DtakoRowsService.CreateRow:input_type -> dtako_rows.CreateRowRequest
	7,  // 16: dtako_rows.DtakoRowsService.UpdateRow:input_type -> dtako_rows.UpdateRowRequest
	9,  // 17: dtako_rows.DtakoRowsService.DeleteRow:input_type -> dtako_rows.DeleteRowRequest
	11, // 18: dtako_rows.DtakoRowsService.SearchRows:input_type -> dtako_rows.SearchRowsRequest
	2,  // 19: dtako_rows.DtakoRowsService.GetRow:output_type -> dtako_rows.GetRowResponse
	4,  // 20: dtako_rows.DtakoRowsService.ListRows:output_type -> dtako_rows.ListRowsResponse
	6,  // 21: dtako_rows.DtakoRowsService.CreateRow:output_type -> dtako_rows.CreateRowResponse
	8,  // 22: dtako_rows.DtakoRowsService.UpdateRow:output_type -> dtako_rows.UpdateRowResponse
	10, // 23: dtako_rows.DtakoRowsService.DeleteRow:output_type -> dtako_rows.DeleteRowResponse
	4,  // 24: dtako_rows.DtakoRowsService.SearchRows:output_type -> dtako_rows.ListRowsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_dtako_rows_proto_init() }
func file_proto_dtako_rows_proto_init() {
	if File_proto_dtako_rows_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dtako_rows_proto_rawDesc), len(file_proto_dtako_rows_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dtako_rows_proto_goTypes,
		DependencyIndexes: file_proto_dtako_rows_proto_depIdxs,
		MessageInfos:      file_proto_dtako_rows_proto_msgTypes,
	}.Build()
	File_proto_dtako_rows_proto = out.File
	file_proto_dtako_rows_proto_goTypes = nil
	file_proto_dtako_rows_proto_depIdxs = nil
}
