// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: dtako_rows_aggregation.proto

package dtako_rows_aggregation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DtakoRowsAggregationService_GetMonthlyFuelConsumption_FullMethodName = "/dtako_rows_aggregation.DtakoRowsAggregationService/GetMonthlyFuelConsumption"
	DtakoRowsAggregationService_GetVehicleMonthlySummary_FullMethodName  = "/dtako_rows_aggregation.DtakoRowsAggregationService/GetVehicleMonthlySummary"
	DtakoRowsAggregationService_GetDailySummary_FullMethodName           = "/dtako_rows_aggregation.DtakoRowsAggregationService/GetDailySummary"
	DtakoRowsAggregationService_ExportMonthlyFuelCSV_FullMethodName      = "/dtako_rows_aggregation.DtakoRowsAggregationService/ExportMonthlyFuelCSV"
)

// DtakoRowsAggregationServiceClient is the client API for DtakoRowsAggregationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DtakoRowsAggregationService - 運行データ集計サービス
type DtakoRowsAggregationServiceClient interface {
	// 車両ごとの月次給油量集計
	GetMonthlyFuelConsumption(ctx context.Context, in *GetMonthlyFuelConsumptionRequest, opts ...grpc.CallOption) (*MonthlyFuelConsumptionResponse, error)
	// 全車両の月次サマリー取得
	GetVehicleMonthlySummary(ctx context.Context, in *GetVehicleMonthlySummaryRequest, opts ...grpc.CallOption) (*VehicleMonthlySummaryResponse, error)
	// 日次サマリー取得
	GetDailySummary(ctx context.Context, in *GetDailySummaryRequest, opts ...grpc.CallOption) (*DailySummaryResponse, error)
	// CSV形式でエクスポート
	ExportMonthlyFuelCSV(ctx context.Context, in *GetMonthlyFuelConsumptionRequest, opts ...grpc.CallOption) (*ExportCSVResponse, error)
}

type dtakoRowsAggregationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDtakoRowsAggregationServiceClient(cc grpc.ClientConnInterface) DtakoRowsAggregationServiceClient {
	return &dtakoRowsAggregationServiceClient{cc}
}

func (c *dtakoRowsAggregationServiceClient) GetMonthlyFuelConsumption(ctx context.Context, in *GetMonthlyFuelConsumptionRequest, opts ...grpc.CallOption) (*MonthlyFuelConsumptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MonthlyFuelConsumptionResponse)
	err := c.cc.Invoke(ctx, DtakoRowsAggregationService_GetMonthlyFuelConsumption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtakoRowsAggregationServiceClient) GetVehicleMonthlySummary(ctx context.Context, in *GetVehicleMonthlySummaryRequest, opts ...grpc.CallOption) (*VehicleMonthlySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VehicleMonthlySummaryResponse)
	err := c.cc.Invoke(ctx, DtakoRowsAggregationService_GetVehicleMonthlySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtakoRowsAggregationServiceClient) GetDailySummary(ctx context.Context, in *GetDailySummaryRequest, opts ...grpc.CallOption) (*DailySummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DailySummaryResponse)
	err := c.cc.Invoke(ctx, DtakoRowsAggregationService_GetDailySummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dtakoRowsAggregationServiceClient) ExportMonthlyFuelCSV(ctx context.Context, in *GetMonthlyFuelConsumptionRequest, opts ...grpc.CallOption) (*ExportCSVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportCSVResponse)
	err := c.cc.Invoke(ctx, DtakoRowsAggregationService_ExportMonthlyFuelCSV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DtakoRowsAggregationServiceServer is the server API for DtakoRowsAggregationService service.
// All implementations must embed UnimplementedDtakoRowsAggregationServiceServer
// for forward compatibility.
//
// DtakoRowsAggregationService - 運行データ集計サービス
type DtakoRowsAggregationServiceServer interface {
	// 車両ごとの月次給油量集計
	GetMonthlyFuelConsumption(context.Context, *GetMonthlyFuelConsumptionRequest) (*MonthlyFuelConsumptionResponse, error)
	// 全車両の月次サマリー取得
	GetVehicleMonthlySummary(context.Context, *GetVehicleMonthlySummaryRequest) (*VehicleMonthlySummaryResponse, error)
	// 日次サマリー取得
	GetDailySummary(context.Context, *GetDailySummaryRequest) (*DailySummaryResponse, error)
	// CSV形式でエクスポート
	ExportMonthlyFuelCSV(context.Context, *GetMonthlyFuelConsumptionRequest) (*ExportCSVResponse, error)
	mustEmbedUnimplementedDtakoRowsAggregationServiceServer()
}

// UnimplementedDtakoRowsAggregationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDtakoRowsAggregationServiceServer struct{}

func (UnimplementedDtakoRowsAggregationServiceServer) GetMonthlyFuelConsumption(context.Context, *GetMonthlyFuelConsumptionRequest) (*MonthlyFuelConsumptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonthlyFuelConsumption not implemented")
}
func (UnimplementedDtakoRowsAggregationServiceServer) GetVehicleMonthlySummary(context.Context, *GetVehicleMonthlySummaryRequest) (*VehicleMonthlySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVehicleMonthlySummary not implemented")
}
func (UnimplementedDtakoRowsAggregationServiceServer) GetDailySummary(context.Context, *GetDailySummaryRequest) (*DailySummaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailySummary not implemented")
}
func (UnimplementedDtakoRowsAggregationServiceServer) ExportMonthlyFuelCSV(context.Context, *GetMonthlyFuelConsumptionRequest) (*ExportCSVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportMonthlyFuelCSV not implemented")
}
func (UnimplementedDtakoRowsAggregationServiceServer) mustEmbedUnimplementedDtakoRowsAggregationServiceServer() {
}
func (UnimplementedDtakoRowsAggregationServiceServer) testEmbeddedByValue() {}

// UnsafeDtakoRowsAggregationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DtakoRowsAggregationServiceServer will
// result in compilation errors.
type UnsafeDtakoRowsAggregationServiceServer interface {
	mustEmbedUnimplementedDtakoRowsAggregationServiceServer()
}

func RegisterDtakoRowsAggregationServiceServer(s grpc.ServiceRegistrar, srv DtakoRowsAggregationServiceServer) {
	// If the following call pancis, it indicates UnimplementedDtakoRowsAggregationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DtakoRowsAggregationService_ServiceDesc, srv)
}

func _DtakoRowsAggregationService_GetMonthlyFuelConsumption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyFuelConsumptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtakoRowsAggregationServiceServer).GetMonthlyFuelConsumption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DtakoRowsAggregationService_GetMonthlyFuelConsumption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtakoRowsAggregationServiceServer).GetMonthlyFuelConsumption(ctx, req.(*GetMonthlyFuelConsumptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DtakoRowsAggregationService_GetVehicleMonthlySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVehicleMonthlySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtakoRowsAggregationServiceServer).GetVehicleMonthlySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DtakoRowsAggregationService_GetVehicleMonthlySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtakoRowsAggregationServiceServer).GetVehicleMonthlySummary(ctx, req.(*GetVehicleMonthlySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DtakoRowsAggregationService_GetDailySummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailySummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtakoRowsAggregationServiceServer).GetDailySummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DtakoRowsAggregationService_GetDailySummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtakoRowsAggregationServiceServer).GetDailySummary(ctx, req.(*GetDailySummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DtakoRowsAggregationService_ExportMonthlyFuelCSV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMonthlyFuelConsumptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DtakoRowsAggregationServiceServer).ExportMonthlyFuelCSV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DtakoRowsAggregationService_ExportMonthlyFuelCSV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DtakoRowsAggregationServiceServer).ExportMonthlyFuelCSV(ctx, req.(*GetMonthlyFuelConsumptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DtakoRowsAggregationService_ServiceDesc is the grpc.ServiceDesc for DtakoRowsAggregationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DtakoRowsAggregationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dtako_rows_aggregation.DtakoRowsAggregationService",
	HandlerType: (*DtakoRowsAggregationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonthlyFuelConsumption",
			Handler:    _DtakoRowsAggregationService_GetMonthlyFuelConsumption_Handler,
		},
		{
			MethodName: "GetVehicleMonthlySummary",
			Handler:    _DtakoRowsAggregationService_GetVehicleMonthlySummary_Handler,
		},
		{
			MethodName: "GetDailySummary",
			Handler:    _DtakoRowsAggregationService_GetDailySummary_Handler,
		},
		{
			MethodName: "ExportMonthlyFuelCSV",
			Handler:    _DtakoRowsAggregationService_ExportMonthlyFuelCSV_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dtako_rows_aggregation.proto",
}
